# Generated by Django 6.0.4 on 2026-04-23 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='repos.issue'),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repository',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='starred_repos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='repos.repository'),
        ),
        migrations.AddField(
            model_name='star',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.repository'),
        ),
        migrations.AddField(
            model_name='star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('repo', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='star',
            unique_together={('user', 'repo')},
        ),
    ]
