# Generated by Django 6.0.3 on 2026-04-23 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='repos/')),
                ('size', models.IntegerField()),
                ('branch', models.CharField(default='main', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repos.repository')),
            ],
            options={
                'ordering': ['path'],
                'unique_together': {('repo', 'path', 'branch')},
            },
        ),
    ]
